### ISSUE TITLE
Dead Docker image URL

### ISSUE THREAD

**Issue by kovmir** [lcomrade/lenpaste#10]
`git.lcomrade.su/root/lenpaste:latest` within `docker-compose.yml` is dead.

**Comment by lcomrade** [comment]
Yes, indeed git.lcomrade.su is no longer available and neither is the image located there. The image is now at ghcr.io, for example the latest version is `ghcr.io/lcomrade/lenpaste:1.3.1`.

Just replace `git.lcomrade.su/root/lenpaste:latest` with `ghcr.io/lcomrade/lenpaste:1.3.1` and everything will work as before. 

PS: I have already corrected references to the old image in README.
