### ISSUE TITLE
Can't pull img

### ISSUE THREAD

**Issue by kWAYTV** [lcomrade/lenpaste#13]
![image](https://github.com/lcomrade/lenpaste/assets/55437151/afa1e3b6-113b-4a6b-8dc4-f4ed6b473450)
![image](https://github.com/lcomrade/lenpaste/assets/55437151/aa107744-3f48-4d9e-9f6e-594d75d87ea2)

**Comment by lcomrade** [comment]
You are trying to download a Docker image from a host that is no longer running. Replace `git.lcomrade.su/root/lenpaste:latest` with `ghcr.io/lcomrade/lenpaste:1.3.1`.

**Comment by kWAYTV** [comment]
> You are trying to download a Docker image from a host that is no longer running. Replace `git.lcomrade.su/root/lenpaste:latest` with `ghcr.io/lcomrade/lenpaste:1.3.1`.

can't i use `:lastest`?

**Comment by lcomrade** [comment]
No, you can't. I gave up on `latest` as that tag can cause an unintended update.

There is no guarantee that version `1.3` will be compatible with `1.4`. There may be different configuration flags or no SQLite support. So to avoid unexpected crashes during use I removed the `latest` tag.

**Comment by kWAYTV** [comment]
> No, you can't. I gave up on `latest` as that tag can cause an unintended update.
> 
> There is no guarantee that version `1.3` will be compatible with `1.4`. There may be different configuration flags or no SQLite support. So to avoid unexpected crashes during use I removed the `latest` tag.

Alright mate thank you a lot!
